### PR TITLE
Adding tufte-ebook

### PR DESCRIPTION
**Pull request by elbamos**
I made a few modifications to try to move this toward the new features in `tufte`, otherwise its the same code that's been in use in rticles. 

Please let me know your view on dependencies.  I felt it was valuable to have a template that demonstrated how to do a lot of things, what packages to use for what kind of pretty output, because they were things that I had spent a long time trying to figure out.  But, the `rticles` maintainers were not thrilled about that, and I was getting ready to bite the bullet and take them out. 

It would be nice if the `marginfigure` environment worked with this, and if all three classes supported things like `margintable`, captions on `marginfigures`, etc.  I took a quick stab at that tonight, and it looks like its going to be a few hours' work.  I'd like to get the template committed into the package before doing that.

### CODE REVIEW

**Comment by elbamos** [comment]
Oh - One thing I forgot, with some TeX installs the skeleton has trouble building on Windows.  The culprit is Bettina Gruen's umlaut.  It isn't a big deal to take that out of the skel, just letting you know.

**Comment by yihui** [comment]
Thanks! I can see qutie a few things that can be improved. Instead of going back and forth between you and me in this PR, do you mind if I just make changes based on your commit?

1. `tufte_ebook()` is basically the same thing as `tufte_handout()`; I'd prefer not cuting-and-pasting so large a portion of code. I think it is simple to reuse `tufte_handout()` here.
1. If it is possible to leave out tufte-common.def and tufte.bst, I'd leave them out and let users install the `tufte-latex` package. I want to maintain as few things as possible and focus on the R side only (leave the responsibility of maintaining the LaTeX packages in the hands of these packages).
1. It is fine to mention those add-on packages in skeleton.Rmd, but I'd not really use them. It is a little frustrating that the example does not compile out of box.
1. Ideally I hope the same skeleton.Rmd for `tufte_html` can be compiled to a book, so we do not need to maintain a separate Rmd example. Personally I do not like seeing a lot of backslashes (LaTeX commands and environments) in an R Markdown document. Some LaTeX features may appealing, but  my own priority is portability. It will be nice if the official example can be converted to HTML, a PDF handout, and a PDF book without changing anything in the content. Some issues can be solved by using R helper functions such as `newthought()`, some can be solved using Pandoc (e.g. the command-line option `--chapters` instead of `\chapter{}`), and some just have to be avoided if users want different types of output.

**Comment by elbamos** [comment]
Thanks, @yihui 

I don't mind if you make changes, of course, but I would kind of like to get the ultimate commit... :p   

However I don't think some of the things you suggest would accomplish the intended goals. 

Regarding your comments --
1.   The classes seem similar, and when I first started the project I thought they'd be basically the same, but it turns out they're not.  

`tufte-book` is mostly a feature-superset of `tufte-handout`, with a LOT more latex capability.  But the original class authors intended to force certain style choices, so `tufte-handout` and `tufte-book` each have some things hard-coded in that conflict with each other.   `tufte-ebook` tries to remove a bunch of those hard-coded limitations, while adding a few things.  So `ebook` is kind of a superset of `book`.

Anything you can do in `handout`, it should be possible to do in `ebook`, I think.  But the reverse isn't true, I'm pretty sure.  

It also seems the only payoff would be eliminating one .tex file, so I wonder if the book is worth the candle.

2.   Agreed.  I don't know latex well enough to say whether its possible to leave them out. 

3.   Agreed.  Should the latex examples stay in though?  

It would be nice if somewhere someone made a gallery of how output looks from all the different R latex packages, but the place for that isn't this skeleton.

4.  I'm not sure I completely understand?   It looks to me that the HTML skeleton does compile properly to `ebook.`  It should, since the `ebook` features are a superset of the `handout` features.  

But the reverse isn't true -- I don't see how you could do the things in the HTML class that are possible in `ebook`.  

I completely agree that the `ebook` features would be much better implemented as R functions or environments, the way you did newthought() and marginfigure.  I don't like the backslashes either.  

I started down that path last night, and it's going to be some work in both directions though.  For example, text in landscape mode.  I'm not sure how you'd make one page of HTML landscaped.  For another, the `margintable` environment, which is highly non-trivial, I don't think would work in `tufte-handout` without some changes to the class, and I'm not sure what would be entailed in getting it to work in HTML.  (I'm not an HTML/CSS guy.)  `multicols`...   

Also, it doesn't look to me that the current R implementations of `marginfigure`, etc., support captions?

**Comment by yihui** [comment]
I'll send you a PR to show you what I was thinking.

It is certainly not possible to replace LaTeX with Markdown. The goal is to achieve as much as possible with pure Markdown. When this is not possible, we introduce a little bit complexity by using R (`fig.margin = TRUE` and `newthought()` are such examples). When it is still difficult even with R helpers, I'd just give up (examples include `marginefigure` with caption, the landscape mode, and multicols). If users really want such features, their last resort is the evil backslashes :) They just need to be aware that once they go down this path, they will lose the possibility of HTML output. That may be totally fine, if one only cares about PDF output. From my perspective, I only care about three things in the tufte style: 1) simple side/margin notes; 2) figure/table captions in the margin; 3) fullwidth figures. Other features can be documented as "possible with LaTeX commands but we do not have a native and portable way to express them".

**Pull request closed without merging**
