### PR TITLE
Added runtitle option to allow running headers to be specified in yaml

### PR DESCRIPTION
**Pull request by puterleat**
I'll send the contributor form by email.

### CODE REVIEW

**Comment by yihui** [comment]
This change is simple enough that we do not really need an agreement, but it is certainly helpful if you have sent one, since you will not need to send it again the next time when you submit a more substantial PR.

I'm not sure if `shorttitle` or `plaintitle` will be a better name than `runtitle`...

**Comment by ssp3nc3r** [comment]
The code is missing `$$`. Should be, `\title$if(runtitle)$[$runtitle$]$endif${$title$}`

**Comment by yihui** [comment]
@ssp3nc3r You are certainly correct!

**Comment by cderv** [comment]
Done in https://github.com/rstudio/tufte/pull/82

**Pull request closed without merging**
